### PR TITLE
fix[isObjectOf]: no discover prototype properties

### LINKED ISSUE #92: question: `isObjectOf()` intended to check prototype properties?
## Question

`isObjectOf()` checks prototype properties. This is intended?

```typescript
const parent = { a: is.Number };
const child = Object.create(parent);
child.b = is.String;

is.ObjectOf(child)({ a: 0 }); // false
is.ObjectOf(child)({ b: "a" }); // false
is.ObjectOf(child)({ a: 0, b: "a" }); // true
```

## Additional

`isStrictOf()` does not support this behavior.

```typescript
is.StrictOf(is.ObjectOf(child))({ a: 0, b: "a" }); // false
```

## Version
v4.0.1 7d8bcbd

### PR DESCRIPTION
**Pull request by Milly**
Fixes #92

### CODE REVIEW

File: is/object_of_test.ts [hunk 1]
```diff
@@ -98,4 +98,46 @@ Deno.test("isObjectOf<T>", async (t) => {
...
     }
   });
+
+  await t.step("if 'predObj' has prototype properties", async (t) => {
+    const prototypeObj = {
+      a: is.Number,
+      b: is.Boolean,
+    };
+    // deno-lint-ignore ban-types
+    const predObj2 = Object.assign(Object.create(prototypeObj) as {}, {
```
Comment (lambdalisue) [inline is/object_of_test.ts:108]: I prefer to overwrite `predObj` here while this whole step only requires `predObj2` and we don't refer `predObj` of it's parent. (I assumed that overwriting constants in a child scope is accepted in TS, right?)

File: is/object_of_test.ts [hunk 2]
```diff
@@ -98,4 +98,46 @@ Deno.test("isObjectOf<T>", async (t) => {
       >(true);
     }
   });
+
+  await t.step("if 'predObj' has prototype properties", async (t) => {
```
Comment (lambdalisue) [inline is/object_of_test.ts:102]: It should explain the behavior like "prototype properties of 'predObj' does not affect the predication"

File: is/object_of_test.ts [hunk 3]
```diff
@@ -98,4 +98,46 @@ Deno.test("isObjectOf<T>", async (t) => {
...
+    await t.step("returns true on T object that omits prototype", () => {
+      assertEquals(isObjectOf(predObj2)({ c: "a" }), true);
+      assertEquals(
+        isObjectOf(predObj2)({ c: "a", d: "ignored" }),
+        true,
+      );
+      assertEquals(
+        isObjectOf(predObj2)(Object.assign(() => void 0, { c: "a" })),
+        true,
+      );
```
Comment (lambdalisue) [inline is/object_of_test.ts:121]: I'd like to see the result of `{a: "a", b: 0, c: "a"}`. I guess it is `true`, right?

**Review by lambdalisue — CHANGES_REQUESTED** [review]

**Review by lambdalisue — APPROVED** [review]
